# Generated by Django 4.1.3 on 2023-03-21 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Couse',
            new_name='Course',
        ),
    ]
